specVersion: 0.0.1
description: https://twitter.com/GenAsterism
repository: https://github.com/tash-2s/subql-maybe-ga-sale
schema: ./schema.graphql
network:
  endpoint: wss://kusama.api.onfinality.io/public-ws
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 7479313
    mapping:
      handlers:
        - handler: handleCall
          kind: substrate/CallHandler
          filter:
              module: utility
              method: batchAll
              success: true
